name: Commitlint

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  commitlint:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate PR commits with commitlint
      uses: wagoid/commitlint-github-action@v6
